# Generated by Django 3.1.2 on 2020-10-20 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('doj', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('points', models.IntegerField()),
                ('designtion', models.CharField(max_length=20)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.emp')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('file_project', models.FileField(blank=True, null=True, upload_to='files/')),
                ('default_pts', models.IntegerField()),
                ('c_pts', models.IntegerField()),
                ('b_pts', models.IntegerField()),
                ('total', models.IntegerField()),
                ('status', models.BooleanField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('child', models.ManyToManyField(to='Client.Child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.parent')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.project')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pts', models.IntegerField()),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.emp')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.project')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.team')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.emp'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.parent'),
        ),
    ]
