# Generated by Django 3.1.2 on 2020-10-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file_project',
        ),
        migrations.AddField(
            model_name='project',
            name='available_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='checksum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='project_create_file',
            field=models.FileField(blank=True, null=True, upload_to='project_create/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='file_project',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='emp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.emp'),
        ),
    ]
