# Generated by Django 3.1.2 on 2020-10-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20201024_0148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
