# Generated by Django 3.1.2 on 2020-10-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20201027_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='testing_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
