# Generated by Django 3.1.2 on 2020-10-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='emp',
            new_name='user',
        ),
    ]
