# Generated by Django 3.1.2 on 2020-10-21 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Client.organization'),
            preserve_default=False,
        ),
    ]
