# Generated by Django 3.1.2 on 2020-10-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20201022_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting_Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank1', models.IntegerField(default=0)),
                ('rank2', models.IntegerField(default=0)),
                ('rank3', models.IntegerField(default=0)),
                ('checksum', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.emp')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.project')),
            ],
        ),
    ]
