# Generated by Django 3.1.2 on 2020-10-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_submission_testing_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='doj_testing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
