# Generated by Django 3.1.2 on 2020-10-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_delete_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_create_file',
            field=models.FileField(blank=True, null=True, upload_to='projectcreate/'),
        ),
    ]
