# Generated by Django 3.1.2 on 2020-10-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_auto_20201024_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.organization')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='parentproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.parentproject'),
        ),
    ]
