# Generated by Django 3.1.2 on 2020-10-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='checksum',
            field=models.IntegerField(default=0),
        ),
    ]
