# Generated by Django 3.1.2 on 2020-10-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_organization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
