# Generated by Django 3.1.2 on 2020-10-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_auto_20201021_1909'),
        ('Client', '0005_organization_confirmed'),
    ]

    operations = [
    ]
