# Generated by Django 3.1.2 on 2020-10-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_organization_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='desig_set',
            field=models.BooleanField(default=False),
        ),
    ]
