# Generated by Django 3.1.2 on 2020-10-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_submission_checksum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='checksum',
        ),
        migrations.AddField(
            model_name='project',
            name='checksum',
            field=models.IntegerField(default=0),
        ),
    ]
