# Generated by Django 3.1.2 on 2020-10-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_auto_20201025_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentproject',
            name='name',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
