# Generated by Django 3.1.2 on 2020-10-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_merge_20201021_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('after_deadline', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.child')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.team')),
            ],
        ),
    ]
