# Generated by Django 3.1.2 on 2020-10-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_auto_20201023_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='available_points',
            field=models.IntegerField(default=0),
        ),
    ]
