# Generated by Django 3.1.2 on 2020-10-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_auto_20201025_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file_project',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
