# Generated by Django 3.1.2 on 2020-10-22 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_auto_20201022_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='emp',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='age',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='designtion',
        ),
        migrations.AddField(
            model_name='emp',
            name='designation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='emp',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
