# Generated by Django 3.1.2 on 2020-10-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_auto_20201021_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.parent'),
        ),
    ]
