# Generated by Django 3.1.2 on 2020-10-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_auto_20201021_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='emp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.emp'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.parent'),
        ),
    ]
