# Generated by Django 3.1.2 on 2020-10-26 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
