# Generated by Django 3.1.2 on 2020-10-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_auto_20201021_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.emp'),
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ManyToManyField(to='Client.Parent'),
        ),
    ]
