# Generated by Django 3.1.2 on 2020-10-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_auto_20201022_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='designation',
            field=models.TextField(blank=True, default='CEO'),
            preserve_default=False,
        ),
    ]
