# Generated by Django 3.1.2 on 2020-10-22 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0011_auto_20201022_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='emp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.emp'),
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ManyToManyField(blank=True, to='Client.Parent'),
        ),
    ]
