# Generated by Django 3.1.2 on 2020-10-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_auto_20201021_2308'),
        ('Client', '0012_auto_20201021_2315'),
    ]

    operations = [
    ]
