# Generated by Django 3.1.2 on 2020-10-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0013_merge_20201021_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
    ]
