# Generated by Django 3.1.2 on 2020-10-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0015_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
