# Generated by Django 3.1.2 on 2020-10-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0016_auto_20201022_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
