# Generated by Django 3.1.2 on 2020-10-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0018_auto_20201022_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.emp'),
        ),
    ]
