# Generated by Django 3.1.2 on 2020-10-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
