# Generated by Django 3.1.2 on 2020-10-22 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0012_auto_20201022_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('max_reward', models.IntegerField()),
                ('assigned', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.emp')),
            ],
        ),
        migrations.CreateModel(
            name='Taskassigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_points', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('asignment_time', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.emp')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction.task')),
            ],
        ),
        migrations.CreateModel(
            name='Tasksubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction.taskassigned')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.emp')),
            ],
        ),
        migrations.CreateModel(
            name='Tasksubmissionfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_item', models.FileField(upload_to='submission')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction.tasksubmission')),
            ],
        ),
    ]
