# Generated by Django 3.1.2 on 2020-10-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0002_task_attachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasksubmissionfiles',
            new_name='Tasksubmissionfile',
        ),
    ]
