# Generated by Django 3.1.2 on 2020-10-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0012_auto_20201022_1927'),
        ('Auction', '0003_auto_20201023_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskbid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.emp')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction.task')),
            ],
        ),
    ]
