# Generated by Django 3.1.2 on 2020-10-22 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0004_taskbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbid',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
