# Generated by Django 3.1.2 on 2020-10-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0006_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
