# Generated by Django 3.1.2 on 2020-10-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='checksum',
            field=models.IntegerField(default=0),
        ),
    ]
