# Generated by Django 3.1.2 on 2020-10-23 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_auto_20201024_0242'),
        ('Voting', '0002_voting_checksum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='checksum',
        ),
        migrations.CreateModel(
            name='Votechecksum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.IntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.team')),
            ],
        ),
    ]
