# Generated by Django 3.1.2 on 2020-10-23 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0003_auto_20201024_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votechecksum',
            name='team',
        ),
        migrations.AddField(
            model_name='votechecksum',
            name='vote',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Voting.voting'),
            preserve_default=False,
        ),
    ]
