# Generated by Django 3.1.2 on 2020-10-23 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0007_project_available_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoutout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.emp')),
            ],
        ),
    ]
