# Generated by Django 3.1.2 on 2020-10-24 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20201024_0201'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shoutout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoutout',
            name='emp',
        ),
        migrations.AddField(
            model_name='shoutout',
            name='emp_appreciated',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.emp'),
        ),
        migrations.AddField(
            model_name='shoutout',
            name='emp_appreciator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoutout',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.organization'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_likes', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emp_liked', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.emp')),
                ('shoutout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shoutout.shoutout')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emp_commented', models.ManyToManyField(blank=True, to='Client.Emp')),
                ('shoutout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shoutout.shoutout')),
            ],
        ),
    ]
