# Generated by Django 3.1.2 on 2020-10-24 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shoutout', '0002_auto_20201024_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='commentlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoutout',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='shoutoutlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='emp_commented',
        ),
        migrations.AddField(
            model_name='comment',
            name='emp_commented',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
