# Generated by Django 3.1.2 on 2020-10-24 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20201024_0201'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shoutout', '0003_auto_20201024_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoutout',
            name='emp_appreciated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.emp'),
        ),
        migrations.AlterField(
            model_name='shoutout',
            name='emp_appreciator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
